# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftySegmentedControl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftySegmentedControl
  pod 'SwiftySegmentedControl', :path => '../'

  target 'SwiftySegmentedControlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftySegmentedControlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
